### ISSUE TITLE
cannot crawl, cannot walk, cannot run

### ISSUE THREAD

**Issue by ErezBinyamin** [firmadyne/scraper#13] opened 2018-06-21 19:43 UTC
I'm working on a side project with some friends and I stumbled across your scrapy repo. It looks really cool and exactly what I need to scrape the web for a bunch of firmware! I'm unfamiliar with the scrapy package, and your readme's recommendation of:

`scrapy crawl dlink`

has yielded nothing but errors and hanging for me. I'm still reading though scrapy docs and your code, but I'm struggling to get any of the spiders to crawl. I was hoping you might be able to give me some guidance on how to go about using your tool. If there are any config files, scrapy command line options, unlisted dependencies, or other things I might be missing, a bit of direction on how to start web-crawling would help me a lot.

![scarpyerror](https://user-images.githubusercontent.com/22354670/41741677-c0b92fa6-7569-11e8-81e7-0ac8fcda451a.png)

Regardless, thank you for all your work on what looks like an amazing open source tool!

**Comment by ddcc** [comment] 2018-06-21 19:46
Seems to be duplicate of #7. You need to upgrade to newer version of scrapy.

**Closed as completed by ddcc** 2018-06-21 19:46 UTC
