### ISSUE TITLE
Successfully crawl using python3.5, but with no images downloading

### ISSUE THREAD

**Issue by 040840308** [firmadyne/scraper#15] opened 2019-10-06 12:19 UTC
Hi, everyone
 
     I successfully run this code with python3.5, with the following outputs:
     2019-10-06 20:06:12 [scrapy.core.scraper] DEBUG: Scraped from <200 https://s.ssl.qhres.com/static/3bef0d53c1b56012/common_info.js>
{'description': 'ROM\\u6b63\\u5f0f\\u7248\\u3010360\\u5bb6\\u5ead\\u9632\\u706b\\u5899\\u00b7\\u8def\\u7531\\u5668 '
                '5S\\u3011',
 'file_urls': ['http://luyou.dl.qihucdn.com/luyou/360F5S/360-F5S-V3.1.2.64131.bin'],
 'files': [],
 'product': 'f5s',
 'url': 'http://luyou.dl.qihucdn.com/luyou/360F5S/360-F5S-V3.1.2.64131.bin',
 'vendor': '360',
 'version': 'V3.1.2.64131'}

I found that no images are actually downloaded and saved in the output folder.
I did not  install the SQL.  My question is: does this code firstly crawl the  image urls and save them in the SQL, then download the images by iterating the SQL?

Thanks for any reply.

**Comment by ddcc** [comment] 2019-10-07 02:07
No, it should still download them even if there is no SQL server. However, I haven't used or developed this code since it was originally released, so you may need to do some debugging if it doesn't work.

**Comment by 040840308** [comment] 2019-10-07 07:14
OK, I will do some debugging. I run the code on the Win10 with python3.5 and Scrapy 1.7.3

**Comment by ruotongyu** [comment] 2020-10-20 22:16
> OK, I will do some debugging. I run the code on the Win10 with python3.5 and Scrapy 1.7.3

It seems I have the same situation. Would you mind sharing your update if the problem is solved? Thanks for any reply!

**Comment by a798047815** [comment] 2020-12-07 03:57
> > OK, I will do some debugging. I run the code on the Win10 with python3.5 and Scrapy 1.7.3
> 
> It seems I have the same situation. Would you mind sharing your update if the problem is solved? Thanks for any reply!

Hi, have you solved this problem? Can you share how you fix it? Thanks a lot

**Comment by seihtam** [comment] 2021-02-23 11:46
I found the bug and have provided a fix in https://github.com/firmadyne/scraper/pull/24

**Comment by ddcc** [comment] 2021-02-23 19:28
Should be fixed with #24

**Closed as completed by ddcc** 2021-02-23 19:28 UTC
